Repository fossasia/susi_skill_cms, pull requests merged in 2018-06, with the labels that each got.

#722 Fixes #721: Call getRatingsByUser API only when logged-in
  src/components/SkillPage/SkillListing.js
Labels: bug

#715 Add loading animation in design section of botbuilder
  src/components/BotBuilder/BotBuilderPages/Design.js
Labels: enhancement

#725 Fixes #712: Add feature to delete feedback
  src/components/SkillFeedbackCard/SkillFeedbackCard.js
  src/components/SkillPage/SkillListing.js
Labels: feature
